version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nodenet
    depends_on: 
      - node

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 60s && npm init -y && npm install mysql express && node index.js"
    networks:
      - nodenet
    depends_on: 
      - db
    volumes:
      - ./node:/app 
    
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
